
#### VIEWER

GET http://fhir.hl7.pt:8787/fhir/MedicinalProductDefinition?_id=DicTratiopharma25mgFilmtablet-SE-PLC-MedicinalProductDef&_revinclude=RegulatedAuthorization:subject&_include:iterate=RegulatedAuthorization:holder&_revinclude:iterate=Ingredient:for&_revinclude=PackagedProductDefinition:package-for&_include:iterate=PackagedProductDefinition:manufactured-item&_revinclude=AdministrableProductDefinition:form-of&_revinclude:iterate=Ingredient:for&_include:iterate=Ingredient:for&_format=json


#### VIEWER

GET http://fhir.hl7.pt:8787/fhir/MedicinalProductDefinition?_id=7f81d47e-9a74-44b3-8ed7-07990093d878&_revinclude=RegulatedAuthorization:subject&_include:iterate=RegulatedAuthorization:holder&_revinclude:iterate=Ingredient:for&_revinclude=PackagedProductDefinition:package-for&_include:iterate=PackagedProductDefinition:manufactured-item&_revinclude=AdministrableProductDefinition:form-of&_revinclude:iterate=Ingredient:for&_include:iterate=Ingredient:for&_format=json




### teste com * 

GET http://fhir.hl7.pt:8787/fhir/MedicinalProductDefinition?_id=Agen-10mg-Tablet-EE-MPD&_revinclude=PackagedProductDefinition:package-for&_include:iterate=PackagedProductDefinition:*&_format=json


### Get MID
GET http://fhir.hl7.pt:8787/fhir/PackagedProductDefinition?manufactured-item=36b84906-a340-4af5-9225-4cab812e8003

### Get MID - new 
GET http://fhir.hl7.pt:8787/fhir/PackagedProductDefinition?manufactured-item4=36b84906-a340-4af5-9225-4cab812e8003

### Get MID - new 
GET http://fhir.hl7.pt:8787/fhir/PackagedProductDefinition?manufactured-item-new=36b84906-a340-4af5-9225-4cab812e8003


### PPF
GET http://fhir.hl7.pt:8787/fhir/PackagedProductDefinition?_id=j20170630100020#L91


### MID
GET http://fhir.hl7.pt:8787/fhir/ManufacturedItemDefinition/36b84906-a340-4af5-9225-4cab812e8003


#### VIEWER

GET http://fhir.hl7.pt:8787/fhir/Ingredient?for=DicTratiopharma25mgFilmtablet-SE-PLC-ManufacturedItemDef

#### VIEWER

GET http://fhir.hl7.pt:8787/fhir/MedicinalProductDefinition?_id=DicTratiopharma25mgFilmtablet-SE-PLC-MedicinalProductDef&_revinclude:iterate=Ingredient:for&_format=json



### create SP
POST http://fhir.hl7.pt:8787/fhir/SearchParameter 
Content-Type: json

{
  "resourceType": "SearchParameter",
  "id": "ppd-manufacturedItem",
  "status": "active",
  "name": "manufactured-item",
  "description": "Possiblity to search ingredient for PackagedProductDefinition.packaging.containedItem.item.reference",
  "code": "manufactured-item4",
  "base": [
    "PackagedProductDefinition"
  ],
  "type": "reference",
  "expression": "PackagedProductDefinition.packaging.containedItem.item.reference",
  "processingMode": "normal",
  "target": [
        "ManufacturedItemDefinition"
    ]
}





### mark all for reindex
POST http://fhir.hl7.pt:8787/fhir/$mark-all-resources-for-reindexing

### reindex

POST http://fhir.hl7.pt:8787/fhir/$reindex

### look SP
GET  http://fhir.hl7.pt:8787/fhir/SearchParameter 

### delete all and restart
DELETE http://fhir.hl7.pt:8787/fhir/SearchParameter/12059


###new viewer

GET http://fhir.hl7.pt:8787/fhir/MedicinalProductDefinition?_id=7f81d47e-9a74-44b3-8ed7-07990093d878&_revinclude=RegulatedAuthorization:subject&_include:iterate=RegulatedAuthorization:holder&_revinclude=PackagedProductDefinition:package-for&_include:iterate=PackagedProductDefinition:*&_revinclude=AdministrableProductDefinition:form-of&_revinclude:iterate=Ingredient:for&_format=json

###
GET http://fhir.hl7.pt:8787/fhir/Patient


### testing 

POST http://fhir.hl7.pt:8787/fhir/Condition
Content-Type: json

{
  "resourceType" : "Condition",
  "id" : "example",
  "text" : {
    "status" : "generated",
    "div" : "<div xmlns=\"http://www.w3.org/1999/xhtml\">Severe burn of left ear (Date: 24-May 2012)</div>"
  },
  "clinicalStatus" : {
    "coding" : [{
      "system" : "http://terminology.hl7.org/CodeSystem/condition-clinical",
      "code" : "active"
    }]
  },
  "verificationStatus" : {
    "coding" : [{
      "system" : "http://terminology.hl7.org/CodeSystem/condition-ver-status",
      "code" : "confirmed"
    }]
  },
  "category" : [{
    "coding" : [{
      "system" : "http://terminology.hl7.org/CodeSystem/condition-category",
      "code" : "encounter-diagnosis",
      "display" : "Encounter Diagnosis"
    },
    {
      "system" : "http://snomed.info/sct",
      "code" : "439401001",
      "display" : "Diagnosis"
    }]
  }],
  "severity" : {
    "coding" : [{
      "system" : "http://snomed.info/sct",
      "code" : "24484000",
      "display" : "Severe"
    }]
  },
  "code" : {
    "coding" : [{
      "system" : "http://snomed.info/sct",
      "code" : "39065001",
      "display" : "Burn of ear"
    }],
    "text" : "Burnt Ear"
  },
  "bodySite" : [{
    "coding" : [{
      "system" : "http://snomed.info/sct",
      "code" : "49521004",
      "display" : "Left external ear structure"
    }],
    "text" : "Left Ear"
  }],
  "subject" : {
    "reference" : "Patient/700"
  },
  "onsetDateTime" : "2012-05-24",
  "evidence":[{"reference":{ "reference" : "ManufacturedItemDefinition/36b84906-a340-4af5-9225-4cab812e8003" }}]
}


###
GET  http://fhir.hl7.pt:8787/fhir/Condition?evidence-detail=36b84906-a340-4af5-9225-4cab812e8003


### Get MID - new 
GET http://fhir.hl7.pt:8787/fhir/PackagedProductDefinition?biological=36b84906-a340-4af5-9225-4cab812e8003

### Get MID - new 
GET http://fhir.hl7.pt:8787/fhir/PackagedProductDefinition?contained-item=36b84906-a340-4af5-9225-4cab812e8003

### Get MID - new 
GET http://fhir.hl7.pt:8787/fhir/PackagedProductDefinition?device=36b84906-a340-4af5-9225-4cab812e8003

### Get MID - new 
GET http://fhir.hl7.pt:8787/fhir/PackagedProductDefinition?medication=36b84906-a340-4af5-9225-4cab812e8003


### Get MID - new 
GET http://fhir.hl7.pt:8787/fhir/PackagedProductDefinition?package=36b84906-a340-4af5-9225-4cab812e8003

### Get MID - new 
GET http://fhir.hl7.pt:8787/fhir/PackagedProductDefinition?nutrition=36b84906-a340-4af5-9225-4cab812e8003


### create SP
POST http://fhir.hl7.pt:8787/fhir/SearchParameter 
Content-Type: json

{
  "resourceType": "SearchParameter",
  "status": "active",
  "name": "manufactured-item",
  "description": "Possiblity to search ingredient for PackagedProductDefinition.packaging.containedItem.item.reference",
  "code": "manufactured-item",
  "base": [
    "PackagedProductDefinition"
  ],
  "type": "reference",
  "expression": "PackagedProductDefinition.packaging.containedItem.item.reference",
  "processingMode": "normal"
}



### 
GET https://server.fire.ly/r5/PackagedProductDefinition


### post manufactured
PUT https://server.fire.ly/r5/ManufacturedItemDefinition/36b84906-a340-4af5-9225-4cab812e8003
Content-Type: application/json

{
  "resourceType": "ManufacturedItemDefinition",
  "id": "36b84906-a340-4af5-9225-4cab812e8003",
  "meta": {
    "versionId": "3",
    "lastUpdated": "2023-11-22T20:55:53.308+00:00",
    "source": "#Avyd8oP6TyfiJ1mf",
    "profile": [
      "http://unicom-project.eu/fhir/StructureDefinition/PPLManufacturedItemDefinition"
    ]
  },
  "extension": [
    {
      "url": "http://ema.europa.eu/fhir/extension/subject",
      "valueReference": {
        "reference": "MedicinalProductDefinition/7f81d47e-9a74-44b3-8ed7-07990093d878"
      }
    }
  ],
  "status": "active",
  "manufacturedDoseForm": {
    "coding": [
      {
        "system": "https://spor.ema.europa.eu/v1/lists/200000000004",
        "code": "100000073665",
        "display": "Film-coated tablet"
      }
    ]
  },
  "unitOfPresentation": {
    "coding": [
      {
        "system": "https://spor.ema.europa.eu/v1/lists/200000000014",
        "code": "200000002152",
        "display": "Tablet"
      }
    ]
  }
}

### post manufactured
PUT https://server.fire.ly/r5/PackagedProductDefinition/j20170630100020
Content-Type: application/json


{
        "resourceType": "PackagedProductDefinition",
        "id": "j20170630100020",
        "meta": {
          "versionId": "4",
          "lastUpdated": "2023-11-22T20:57:18.636+00:00",
          "source": "#A0f1s2a6XMNEWDSx",
          "profile": [
            "http://unicom-project.eu/fhir/StructureDefinition/PPLPackagedProductDefinition"
          ]
        },
        "language": "EN",
        "identifier": [
          {
            "system": "http://ema.europa.eu/fhir/pcId",
            "value": "SE-100002602-00000001-002"
          }
        ],
        "packageFor": [
          {
            "reference": "MedicinalProductDefinition/7f81d47e-9a74-44b3-8ed7-07990093d878"
          }
        ],
        "containedItemQuantity": [
          {
            "value": 10,
            "unit": "tablets"
          }
        ],
        "description": "Blister 10 tablets",
        "marketingStatus": [
          {
            "country": {
              "coding": [
                {
                  "system": "https://spor.ema.europa.eu/v1/lists/100000000002",
                  "code": "100000000535",
                  "display": "Sweden"
                }
              ]
            },
            "status": {
              "coding": [
                {
                  "system": "https://spor.ema.europa.eu/v1/lists/100000072052",
                  "code": "100000072074",
                  "display": "Not marketed"
                }
              ]
            },
            "dateRange": {
              "start": "2017-06-15"
            }
          }
        ],
        "packaging": {
          "type": {
            "coding": [
              {
                "system": "https://spor.ema.europa.eu/v1/lists/100000073346",
                "code": "100000073498",
                "display": "Box"
              }
            ]
          },
          "quantity": 1,
          "material": [
            {
              "coding": [
                {
                  "system": "https://spor.ema.europa.eu/v1/lists/200000003199",
                  "code": "200000003529",
                  "display": "Cardboard"
                }
              ]
            }
          ],
          "packaging": [
            {
              "type": {
                "coding": [
                  {
                    "system": "https://spor.ema.europa.eu/v1/lists/100000073346",
                    "code": "100000073496",
                    "display": "Blister"
                  }
                ]
              },
              "quantity": 1,
              "material": [
                {
                  "coding": [
                    {
                      "system": "https://spor.ema.europa.eu/v1/lists/200000003199",
                      "code": "200000003200",
                      "display": "Aluminium"
                    }
                  ]
                }
              ],
              "containedItem": [
                {
                  "item": {
                    "reference": {
                      "reference": "ManufacturedItemDefinition/36b84906-a340-4af5-9225-4cab812e8003"
                    }
                  },
                  "amount": {
                    "value": 10
                  }
                }
              ]
            }
          ]
        }}

### Get MID
GET https://server.fire.ly/r5/PackagedProductDefinition?manufactured-item=36b84906-a340-4af5-9225-4cab812e8003


### Get MID
GET https://server.fire.ly/r5/MedicinalProductDefinition/


### Get MID
PUT https://server.fire.ly/r5/Organization/LOC-100043821
Content-Type: application/fhir+json

{
  "resourceType": "Organization",
  "id": "LOC-100043821",
  "meta": {
    "profile": [
      "http://unicom-project.eu/fhir/StructureDefinition/PPLOrganization"
    ]
  },
  "identifier": [
    {
      "system": "https://spor.ema.europa.eu/v1/locations",
      "value": "LOC-100043821"
    }
  ],
  "name": "Bayer AB"
}


### Get hapi data
GET http://hapi.fhir.org/baseR5/MedicinalProductDefinition/




###new viewer

GET https://server.fire.ly/r5/MedicinalProductDefinition?_id=7f81d47e-9a74-44b3-8ed7-07990093d878&_revinclude=RegulatedAuthorization:subject&_include:iterate=RegulatedAuthorization:holder&_revinclude=PackagedProductDefinition:package-for&_include:iterate=PackagedProductDefinition:*&_revinclude=AdministrableProductDefinition:form-of&_revinclude:iterate=Ingredient:for&_format=json


#### VIEWER

GET https://server.fire.ly/r5/MedicinalProductDefinition?_id=7f81d47e-9a74-44b3-8ed7-07990093d878&_revinclude=RegulatedAuthorization:subject&_include:iterate=RegulatedAuthorization:holder&_revinclude=PackagedProductDefinition:package-for&_include:iterate=PackagedProductDefinition:manufactured-item&_revinclude=AdministrableProductDefinition:form-of&_revinclude:iterate=Ingredient:for&_format=json

### Get MID
GET https://server.fire.ly/r5/PackagedProductDefinition?manufactured-item=36b84906-a340-4af5-9225-4cab812e8003



### wtf???

GET https://jpa.unicom.datawizard.it/fhir/MedicinalProductDefinition?_id=ABIS-tablet-10mg--0-ITA-MPD&_revinclude=RegulatedAuthorization:subject&_include:iterate=RegulatedAuthorization:holder&_revinclude=PackagedProductDefinition:package-for&_include:iterate=PackagedProductDefinition:*&_revinclude=AdministrableProductDefinition:form-of&_revinclude:iterate=Ingredient:for&_format=json



### more tests

GET https://jpa.unicom.datawizard.it/fhir/PackagedProductDefinition?medication=ABIS-tablet-10mg--0-ITA-MI


#### VIEWER

GET http://fhir.hl7.pt:8787/fhir/MedicinalProductDefinition?_id=7f81d47e-9a74-44b3-8ed7-07990093d878&_revinclude=RegulatedAuthorization:subject&_include:iterate=RegulatedAuthorization:holder&_revinclude=PackagedProductDefinition:package-for&_include:iterate=PackagedProductDefinition:*&_revinclude=AdministrableProductDefinition:form-of&_revinclude:iterate=Ingredient:for&_format=json


#### VIEWER

GET http://fhir.hl7.pt:8787/fhir/MedicinalProductDefinition?_id=ABIS-tablet-10mg--0-ITA-MPD&_revinclude=RegulatedAuthorization:subject&_include:iterate=RegulatedAuthorization:holder&_revinclude=PackagedProductDefinition:package-for&_include:iterate=PackagedProductDefinition:*&_revinclude=AdministrableProductDefinition:form-of&_revinclude:iterate=Ingredient:for&_format=json

### wtf???

GET https://jpa.unicom.datawizard.it/fhir/SearchParameter/

### test 

DELETE http://fhir.hl7.pt:8787/fhir/AdministrableProductDefinition/5518a708-50e4-46eb-bd47-fc7915290566



### testing with post:

PUT http://fhir.hl7.pt:8787/fhir/AdministrableProductDefinition/5518a708-50e4-46eb-bd47-fc7915290566
Content-Type: application/json

{
  "resourceType": "AdministrableProductDefinition",
  "id": "5518a708-50e4-46eb-bd47-fc7915290566",
  "meta": {
    "profile": [
      "http://unicom-project.eu/fhir/StructureDefinition/PPLAdministrableProductDefinition"
    ]
  },
  "status": "active",
  "formOf": [
    {
      "reference": "MedicinalProductDefinition/7f81d47e-9a74-44b3-8ed7-07990093d878"
    }
  ],
  "administrableDoseForm": {
    "coding": [
      {
        "system": "https://spor.ema.europa.eu/v1/lists/200000000004",
        "code": "100000073665",
        "display": "Film-coated tablet"
      }
    ]
  },
  "unitOfPresentation": {
    "coding": [
      {
        "system": "https://spor.ema.europa.eu/v1/lists/200000000014",
        "code": "200000002152",
        "display": "Tablet"
      }
    ]
  },
  "routeOfAdministration": [
    {
      "code": {
        "coding": [
          {
            "system": "https://spor.ema.europa.eu/v1/lists/100000073345",
            "code": "100000073619",
            "display": "Oral use"
          }
        ]
      }
    }
  ],
      
  "producedFrom": [ {
        "reference": "ManufacturedItemDefinition/36b84906-a340-4af5-9225-4cab812e8003"
      } ]
}

### test 

GET http://fhir.hl7.pt:8787/fhir/ManufacturedItemDefinition/36b84906-a340-4af5-9225-4cab812e8003



##### blacklist delete

DELETE  http://fhir.hl7.pt:8787/fhir/MedicinalProductDefinition/7f81d47e-9a74-44b3-8ed7-07990093d878

##### blacklist delete

DELETE  http://fhir.hl7.pt:8787/fhir/RegulatedAuthorization/33c2e253-9fa1-4e25-a139-421b08cec073 

####
DELETE http://fhir.hl7.pt:8787/fhir/AdministrableProductDefinition/5518a708-50e4-46eb-bd47-fc7915290566 

####
DELETE http://fhir.hl7.pt:8787/fhir/PackagedProductDefinition/j20170630100099

###
GET  http://fhir.hl7.pt:8787/fhir//MedicinalProductDefinition?_id=Agen-10mg-Tablet-EE-MPD&_revinclude=RegulatedAuthorization:subject&_include:iterate=RegulatedAuthorization:holder&_revinclude:iterate=Ingredient:for&_revinclude=PackagedProductDefinition:package-for&_include:iterate=PackagedProductDefinition:manufactured-item&_revinclude=AdministrableProductDefinition:form-of&_revinclude:iterate=Ingredient:for&_include:iterate=Ingredient:for&_format=json