Instance: GOFSH-GENERATED-ID-4
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = Altermol-500mg30mg-Tablet-SE-IS-MedicinalProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/Altermol-500mg30mg-Tablet-SE-IS-MedicinalProductDefinition"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-RegulatedAuthorization
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/Altermol-500mg30mg-Tablet-SE-IS-RegulatedAuthorization"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-AdministrableProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "AdministrableProductDefinition/Altermol-500mg30mg-Tablet-SE-IS-AdministrableProductDefinition"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition01
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition01"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition02
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition02"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition03
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition03"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition04
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition04"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-ManufacturedItemDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/Altermol-500mg30mg-Tablet-SE-IS-ManufacturedItemDefinition"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient01"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient02"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-Ingredient03
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient03"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-Ingredient04
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient04"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-Ingredient05
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient05"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-Ingredient06
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient06"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-Ingredient07
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient07"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-Ingredient08
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient08"