Instance: GOFSH-GENERATED-ID-218
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = Tiparol50mgbrustablett-SE-PLC-MedicinalProductDef
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/Tiparol50mgbrustablett-SE-PLC-MedicinalProductDef"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-RegAutho
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/Tiparol50mgbrustablett-SE-PLC-RegAutho"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-AdminProductDef
* entry[=].request.method = #PUT
* entry[=].request.url = "AdministrableProductDefinition/Tiparol50mgbrustablett-SE-PLC-AdminProductDef"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-PackageProductDef
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Tiparol50mgbrustablett-SE-PLC-PackageProductDef"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-ManufacturedItemDef
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/Tiparol50mgbrustablett-SE-PLC-ManufacturedItemDef"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Tiparol50mgbrustablett-SE-PLC-Ingredient01"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Tiparol50mgbrustablett-SE-PLC-Ingredient02"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-Ingredient03
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Tiparol50mgbrustablett-SE-PLC-Ingredient03"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-Ingredient04
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Tiparol50mgbrustablett-SE-PLC-Ingredient04"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-Ingredient05
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Tiparol50mgbrustablett-SE-PLC-Ingredient05"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-Ingredient06
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Tiparol50mgbrustablett-SE-PLC-Ingredient06"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-Ingredient07
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Tiparol50mgbrustablett-SE-PLC-Ingredient07"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-Ingredient08
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Tiparol50mgbrustablett-SE-PLC-Ingredient08"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-Ingredient09
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Tiparol50mgbrustablett-SE-PLC-Ingredient09"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-Ingredient10
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Tiparol50mgbrustablett-SE-PLC-Ingredient10"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-Ingredient11
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Tiparol50mgbrustablett-SE-PLC-Ingredient11"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-Ingredient12
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Tiparol50mgbrustablett-SE-PLC-Ingredient12"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-Ingredient13
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Tiparol50mgbrustablett-SE-PLC-Ingredient13"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-Ingredient14
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Tiparol50mgbrustablett-SE-PLC-Ingredient14"
* entry[+].resource = Tiparol50mgbrustablett-SE-PLC-Ingredient15
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Tiparol50mgbrustablett-SE-PLC-Ingredient15"