Instance: GOFSH-GENERATED-ID-44
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = Citodon-500mg30mg-EffTablet-SE-IS-MedicinalProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/Citodon-500mg30mg-EffTablet-SE-IS-MedicinalProductDefinition"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-RegulatedAuthorization
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/Citodon-500mg30mg-EffTablet-SE-IS-RegulatedAuthorization"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-AdministrableProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "AdministrableProductDefinition/Citodon-500mg30mg-EffTablet-SE-IS-AdministrableProductDefinition"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-PackagedProductDefinition01
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Citodon-500mg30mg-EffTablet-SE-IS-PackagedProductDefinition01"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-PackagedProductDefinition02
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Citodon-500mg30mg-EffTablet-SE-IS-PackagedProductDefinition02"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-PackagedProductDefinition03
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Citodon-500mg30mg-EffTablet-SE-IS-PackagedProductDefinition03"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-ManufacturedItemDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/Citodon-500mg30mg-EffTablet-SE-IS-ManufacturedItemDefinition"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient01"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient02"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient03
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient03"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient04
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient04"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient05
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient05"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient06
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient06"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient07
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient07"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient08
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient08"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient09
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient09"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient10
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient10"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient11
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient11"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient12
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient12"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient13
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient13"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient14
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient14"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient15
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient15"