Instance: GOFSH-GENERATED-ID-175
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = Oxascand-5mg-Tablet-SE-IS-MedicinalProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/Oxascand-5mg-Tablet-SE-IS-MedicinalProductDefinition"
* entry[+].resource = Oxascand-5mg-Tablet-SE-IS-RegulatedAuthorization
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/Oxascand-5mg-Tablet-SE-IS-RegulatedAuthorization"
* entry[+].resource = Oxascand-5mg-Tablet-SE-IS-AdministrableProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "AdministrableProductDefinition/Oxascand-5mg-Tablet-SE-IS-AdministrableProductDefinition"
* entry[+].resource = Oxascand-5mg-Tablet-SE-IS-PackagedProductDefinition01
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Oxascand-5mg-Tablet-SE-IS-PackagedProductDefinition01"
* entry[+].resource = Oxascand-5mg-Tablet-SE-IS-PackagedProductDefinition02
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Oxascand-5mg-Tablet-SE-IS-PackagedProductDefinition02"
* entry[+].resource = Oxascand-5mg-Tablet-SE-IS-PackagedProductDefinition03
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Oxascand-5mg-Tablet-SE-IS-PackagedProductDefinition03"
* entry[+].resource = Oxascand-5mg-Tablet-SE-IS-PackagedProductDefinition04
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Oxascand-5mg-Tablet-SE-IS-PackagedProductDefinition04"
* entry[+].resource = Oxascand-5mg-Tablet-SE-IS-ManufacturedItemDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/Oxascand-5mg-Tablet-SE-IS-ManufacturedItemDefinition"
* entry[+].resource = Oxascand-5mg-Tablet-SE-IS-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Oxascand-5mg-Tablet-SE-IS-Ingredient01"
* entry[+].resource = Oxascand-5mg-Tablet-SE-IS-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Oxascand-5mg-Tablet-SE-IS-Ingredient02"
* entry[+].resource = Oxascand-5mg-Tablet-SE-IS-Ingredient03
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Oxascand-5mg-Tablet-SE-IS-Ingredient03"
* entry[+].resource = Oxascand-5mg-Tablet-SE-IS-Ingredient04
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Oxascand-5mg-Tablet-SE-IS-Ingredient04"
* entry[+].resource = Oxascand-5mg-Tablet-SE-IS-Ingredient05
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Oxascand-5mg-Tablet-SE-IS-Ingredient05"
* entry[+].resource = Oxascand-5mg-Tablet-SE-IS-Ingredient06
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Oxascand-5mg-Tablet-SE-IS-Ingredient06"