Instance: 0000bba9e466f20debb9a4a09ea9d3d7bba382e95e8b82ec376e7e3d2770569e
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-MedicinalProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/Citodon-500mg30mg-EffTablet-SE-IS-MedicinalProductDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/Citodon-500mg30mg-EffTablet-SE-IS-MedicinalProductDefinition"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-RegulatedAuthorization
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/Citodon-500mg30mg-EffTablet-SE-IS-RegulatedAuthorization"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/Citodon-500mg30mg-EffTablet-SE-IS-RegulatedAuthorization"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-PackagedProductDefinition01
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Citodon-500mg30mg-EffTablet-SE-IS-PackagedProductDefinition01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Citodon-500mg30mg-EffTablet-SE-IS-PackagedProductDefinition01"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-PackagedProductDefinition02
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Citodon-500mg30mg-EffTablet-SE-IS-PackagedProductDefinition02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Citodon-500mg30mg-EffTablet-SE-IS-PackagedProductDefinition02"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-PackagedProductDefinition03
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Citodon-500mg30mg-EffTablet-SE-IS-PackagedProductDefinition03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Citodon-500mg30mg-EffTablet-SE-IS-PackagedProductDefinition03"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-ManufacturedItemDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/Citodon-500mg30mg-EffTablet-SE-IS-ManufacturedItemDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/Citodon-500mg30mg-EffTablet-SE-IS-ManufacturedItemDefinition"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient01"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient02"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient03
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient03"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient04
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient04"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient05
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient05"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient05"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient06
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient06"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient06"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient07
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient07"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient07"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient08
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient08"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient08"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient09
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient09"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient09"
* entry[+].resource = Citodon-500mg30mg-EffTablet-SE-IS-Ingredient10
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient10"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Citodon-500mg30mg-EffTablet-SE-IS-Ingredient10"